import type { AskResource } from './types'

/** Curated help desk links — extend here or move to Supabase later. */
export const ASK_RESOURCES: AskResource[] = [
  {
    id: 'gs-dashboard',
    title: 'Open your Kanban board',
    description: 'Jump to the home board to see tasks, columns, and what to pick up next.',
    url: '/',
    category: 'getting-started',
    kind: 'link',
    tags: ['board', 'home', 'tasks', 'kanban'],
  },
  {
    id: 'gs-settings',
    title: 'Complete your profile',
    description: 'Add your name, avatar, and team settings so teammates recognize you.',
    url: '/settings',
    category: 'getting-started',
    kind: 'tutorial',
    tags: ['profile', 'onboarding', 'account'],
  },
  {
    id: 'gs-network',
    title: 'Find teammates',
    description: 'Use the peer network to connect with classmates before creating a group.',
    url: '/network',
    category: 'getting-started',
    kind: 'tutorial',
    tags: ['team', 'network', 'invite'],
  },
  {
    id: 'gs-docs-start',
    title: 'Espeezy quick start guide',
    description: 'Step-by-step walkthrough for signing up, teams, and your first board.',
    url: '/docs/getting-started',
    category: 'getting-started',
    kind: 'doc',
    tags: ['documentation', 'start', 'guide'],
  },
  {
    id: 'gs-pricing',
    title: 'Plans and premium features',
    description: 'Compare free and premium tiers, school verification, and upgrades.',
    url: '/pricing',
    category: 'getting-started',
    kind: 'doc',
    tags: ['premium', 'billing', 'school email'],
  },
  {
    id: 'gs-contact',
    title: 'Contact support',
    description: 'Reach the Espeezy team for account, billing, or accessibility issues.',
    url: '/contact',
    category: 'getting-started',
    kind: 'link',
    tags: ['help', 'support', 'email'],
  },
  {
    id: 'tut-kanban-basics',
    title: 'Kanban workflow basics',
    description: 'Learn To Do → In Progress → In Review → Done and how assignees work.',
    url: '/docs/features/kanban',
    category: 'tutorials',
    kind: 'tutorial',
    tags: ['kanban', 'workflow', 'columns'],
  },
  {
    id: 'tut-roadmap',
    title: 'Roadmap and intervals',
    description: 'Plan milestones and intervals so the team shares one timeline.',
    url: '/product/roadmap',
    category: 'tutorials',
    kind: 'tutorial',
    tags: ['roadmap', 'planning', 'milestones'],
  },
  {
    id: 'tut-analytics',
    title: 'Project stats walkthrough',
    description: 'Read velocity, completion rates, and contribution metrics for your group.',
    url: '/analytics',
    category: 'tutorials',
    kind: 'tutorial',
    tags: ['analytics', 'metrics', 'stats'],
  },
  {
    id: 'tut-notifications',
    title: 'Notification center',
    description: 'See mentions, task updates, and break-room invites in one inbox.',
    url: '/notifications',
    category: 'tutorials',
    kind: 'tutorial',
    tags: ['notifications', 'inbox', 'alerts'],
  },
  {
    id: 'tut-git-branch',
    title: 'Git branching (Atlassian)',
    description: 'External tutorial on branches, merges, and team git hygiene.',
    url: 'https://www.atlassian.com/git/tutorials/using-branches',
    category: 'tutorials',
    kind: 'tutorial',
    tags: ['git', 'branch', 'merge'],
    external: true,
  },
  {
    id: 'tut-md-markdown',
    title: 'Markdown quick reference',
    description: 'Format task descriptions, docs, and comments with lightweight markup.',
    url: 'https://www.markdownguide.org/cheat-sheet/',
    category: 'tutorials',
    kind: 'tutorial',
    tags: ['markdown', 'writing', 'format'],
    external: true,
  },
  {
    id: 'tut-react-learn',
    title: 'React — Learn',
    description: 'Official interactive tutorial if you are building on the Espeezy stack.',
    url: 'https://react.dev/learn',
    category: 'tutorials',
    kind: 'tutorial',
    tags: ['react', 'frontend', 'javascript'],
    external: true,
  },
  {
    id: 'tut-typescript-handbook',
    title: 'TypeScript handbook',
    description: 'Types, interfaces, and narrowing — useful for custom scripts and PRs.',
    url: 'https://www.typescriptlang.org/docs/handbook/intro.html',
    category: 'tutorials',
    kind: 'tutorial',
    tags: ['typescript', 'types', 'handbook'],
    external: true,
  },
  {
    id: 'doc-home',
    title: 'Documentation home',
    description: 'Archive of Espeezy features, ELI12 explainers, and architecture notes.',
    url: '/docs',
    category: 'espeezy-docs',
    kind: 'doc',
    tags: ['documentation', 'archive', 'manual'],
  },
  {
    id: 'doc-features',
    title: 'Feature index',
    description: 'Browse all documented capabilities across the Kanban workspace.',
    url: '/docs/features',
    category: 'espeezy-docs',
    kind: 'doc',
    tags: ['features', 'index'],
  },
  {
    id: 'doc-intelligence',
    title: 'Project intelligence',
    description: 'How Espeezy turns task history into reports and health signals.',
    url: '/product/intelligence',
    category: 'espeezy-docs',
    kind: 'doc',
    tags: ['intelligence', 'ai', 'reports'],
  },
  {
    id: 'doc-sync',
    title: 'Real-time sync protocol',
    description: 'How live updates, presence, and persistence work across clients.',
    url: '/product/sync',
    category: 'espeezy-docs',
    kind: 'doc',
    tags: ['realtime', 'sync', 'websocket'],
  },
  {
    id: 'doc-privacy',
    title: 'Privacy policy',
    description: 'What we collect, how long we retain it, and your rights.',
    url: '/privacy',
    category: 'espeezy-docs',
    kind: 'doc',
    tags: ['privacy', 'legal', 'gdpr'],
  },
  {
    id: 'doc-terms',
    title: 'Terms of service',
    description: 'Usage rules, acceptable use, and platform responsibilities.',
    url: '/terms',
    category: 'espeezy-docs',
    kind: 'doc',
    tags: ['terms', 'legal', 'policy'],
  },
  {
    id: 'doc-solutions-teams',
    title: 'Solutions — Teams',
    description: 'How study groups and project teams adopt Espeezy end to end.',
    url: '/solutions/teams',
    category: 'espeezy-docs',
    kind: 'doc',
    tags: ['teams', 'enterprise', 'groups'],
  },
  {
    id: 'doc-solutions-scholars',
    title: 'Solutions — Scholars',
    description: 'Workflow patterns tuned for research and academic deliverables.',
    url: '/solutions/scholars',
    category: 'espeezy-docs',
    kind: 'doc',
    tags: ['scholars', 'research', 'academic'],
  },
  {
    id: 'tool-github',
    title: 'GitHub',
    description: 'Host repos, pull requests, and code reviews for coding tasks.',
    url: 'https://github.com',
    category: 'tools-apis',
    kind: 'tool',
    tags: ['git', 'repository', 'pr'],
    external: true,
  },
  {
    id: 'tool-vscode',
    title: 'Visual Studio Code',
    description: 'Recommended editor with extensions for TypeScript and React.',
    url: 'https://code.visualstudio.com/docs',
    category: 'tools-apis',
    kind: 'tool',
    tags: ['editor', 'ide', 'vscode'],
    external: true,
  },
  {
    id: 'tool-supabase-docs',
    title: 'Supabase documentation',
    description: 'Auth, Postgres, and realtime — the backend Espeezy builds on.',
    url: 'https://supabase.com/docs',
    category: 'tools-apis',
    kind: 'doc',
    tags: ['supabase', 'database', 'auth', 'api'],
    external: true,
  },
  {
    id: 'tool-nextjs-docs',
    title: 'Next.js documentation',
    description: 'App router, layouts, and deployment for the Kanban web app.',
    url: 'https://nextjs.org/docs',
    category: 'tools-apis',
    kind: 'doc',
    tags: ['nextjs', 'react', 'framework'],
    external: true,
  },
  {
    id: 'tool-mdn-js',
    title: 'MDN JavaScript reference',
    description: 'Language reference for scripts, hooks, and browser APIs.',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    category: 'tools-apis',
    kind: 'doc',
    tags: ['javascript', 'mdn', 'reference'],
    external: true,
  },
  {
    id: 'tool-figma',
    title: 'Figma — design handoff',
    description: 'Share UI mocks and specs with teammates on design-heavy tasks.',
    url: 'https://help.figma.com/hc/en-us',
    category: 'tools-apis',
    kind: 'tool',
    tags: ['design', 'ui', 'figma'],
    external: true,
  },
  {
    id: 'tool-postman',
    title: 'Postman learning center',
    description: 'Test REST APIs when building integrations or webhooks.',
    url: 'https://learning.postman.com/docs/introduction/overview/',
    category: 'tools-apis',
    kind: 'tool',
    tags: ['api', 'rest', 'testing'],
    external: true,
  },
  {
    id: 'campus-hustle',
    title: 'Hustle marketplace',
    description: 'Post gigs, apply for tasks, and earn credits on campus work.',
    url: '/hustle',
    category: 'campus',
    kind: 'link',
    tags: ['hustle', 'gigs', 'credits', 'jobs'],
  },
  {
    id: 'campus-hustle-connect',
    title: 'Hustle — connect & trade',
    description: 'Fund escrow, apply, and complete hustle tasks with credit payouts.',
    url: '/hustle/connect',
    category: 'campus',
    kind: 'tutorial',
    tags: ['hustle', 'escrow', 'trade'],
  },
  {
    id: 'campus-marketplace',
    title: 'Campus marketplace',
    description: 'Buy and sell textbooks, gear, and supplies with Espeezy credits.',
    url: '/marketplace',
    category: 'campus',
    kind: 'link',
    tags: ['marketplace', 'buy', 'sell', 'credits'],
  },
  {
    id: 'campus-assets',
    title: 'My assets vault',
    description: 'Storage, marketplace listings, credits ledger, and impact log.',
    url: '/assets',
    category: 'campus',
    kind: 'link',
    tags: ['assets', 'storage', 'vault'],
  },
  {
    id: 'campus-credits',
    title: 'Credit ledger',
    description: 'View balance, funding history, and receipts for campus credits.',
    url: '/account/credits',
    category: 'campus',
    kind: 'doc',
    tags: ['credits', 'wallet', 'payments'],
  },
  {
    id: 'campus-impact',
    title: 'Impact log',
    description: 'Track marketplace and hustle outcomes in one ledger view.',
    url: '/assets/impact',
    category: 'campus',
    kind: 'doc',
    tags: ['impact', 'ledger', 'hustle'],
  },
  {
    id: 'campus-feed',
    title: 'Team feed',
    description: 'Share updates and announcements with your project group.',
    url: '/feed',
    category: 'campus',
    kind: 'link',
    tags: ['feed', 'social', 'updates'],
  },
  {
    id: 'campus-chillout',
    title: 'Break room',
    description: 'Quizzes and chill rooms for team breaks between sprints.',
    url: '/chillout',
    category: 'campus',
    kind: 'link',
    tags: ['break', 'quiz', 'games'],
  },
  {
    id: 'ext-stackoverflow',
    title: 'Stack Overflow',
    description: 'Search error messages and patterns from the wider dev community.',
    url: 'https://stackoverflow.com',
    category: 'external',
    kind: 'link',
    tags: ['debug', 'q&a', 'programming'],
    external: true,
  },
  {
    id: 'ext-coursera-study',
    title: 'Coursera — learning skills',
    description: 'Structured courses when you need depth beyond a quick tutorial.',
    url: 'https://www.coursera.org',
    category: 'external',
    kind: 'video',
    tags: ['courses', 'learning', 'video'],
    external: true,
  },
  {
    id: 'ext-khan',
    title: 'Khan Academy',
    description: 'Math, science, and computing refreshers for coursework support.',
    url: 'https://www.khanacademy.org',
    category: 'external',
    kind: 'video',
    tags: ['math', 'science', 'study'],
    external: true,
  },
  {
    id: 'ext-overleaf',
    title: 'Overleaf',
    description: 'Collaborative LaTeX for papers, reports, and lab write-ups.',
    url: 'https://www.overleaf.com/learn',
    category: 'external',
    kind: 'tool',
    tags: ['latex', 'writing', 'papers'],
    external: true,
  },
  {
    id: 'ext-notion',
    title: 'Notion help center',
    description: 'Notes and wikis when your team keeps specs outside the board.',
    url: 'https://www.notion.com/help',
    category: 'external',
    kind: 'tool',
    tags: ['notes', 'wiki', 'docs'],
    external: true,
  },
  {
    id: 'ext-google-scholar',
    title: 'Google Scholar',
    description: 'Find papers and citations for research-heavy project tasks.',
    url: 'https://scholar.google.com',
    category: 'external',
    kind: 'link',
    tags: ['research', 'citations', 'papers'],
    external: true,
  },
  {
    id: 'ext-ieee',
    title: 'IEEE Xplore',
    description: 'Technical papers and standards for engineering coursework.',
    url: 'https://ieeexplore.ieee.org',
    category: 'external',
    kind: 'link',
    tags: ['ieee', 'engineering', 'papers'],
    external: true,
  },
  {
    id: 'ext-w3c-a11y',
    title: 'W3C accessibility fundamentals',
    description: 'Build inclusive UIs — contrast, labels, and keyboard flows.',
    url: 'https://www.w3.org/WAI/fundamentals/',
    category: 'external',
    kind: 'tutorial',
    tags: ['a11y', 'accessibility', 'wcag'],
    external: true,
  },
  {
    id: 'ext-owasp',
    title: 'OWASP Top 10',
    description: 'Security basics when handling auth, APIs, and user data.',
    url: 'https://owasp.org/www-project-top-ten/',
    category: 'external',
    kind: 'doc',
    tags: ['security', 'owasp', 'web'],
    external: true,
  },
  {
    id: 'ext-npm-docs',
    title: 'npm documentation',
    description: 'Install scripts, workspaces, and publishing for monorepo tasks.',
    url: 'https://docs.npmjs.com',
    category: 'external',
    kind: 'doc',
    tags: ['npm', 'node', 'packages'],
    external: true,
  },
  {
    id: 'ext-canva-learn',
    title: 'Canva Design School',
    description: 'Quick visual design tips for posters, slides, and demos.',
    url: 'https://www.canva.com/learn/',
    category: 'external',
    kind: 'tutorial',
    tags: ['design', 'graphics', 'presentations'],
    external: true,
  },
  {
    id: 'ext-youtube-cs50',
    title: 'CS50 lectures (YouTube)',
    description: 'Harvard intro CS playlist — strong foundations for new coders.',
    url: 'https://www.youtube.com/cs50',
    category: 'external',
    kind: 'video',
    tags: ['cs50', 'computer science', 'video'],
    external: true,
  },
  {
    id: 'jukebox',
    title: 'Jukebox',
    description: 'Shared listening room for focus sessions with your team.',
    url: '/jukebox',
    category: 'campus',
    kind: 'link',
    tags: ['music', 'jukebox', 'focus'],
  },
  {
    id: 'profile-public',
    title: 'Your public profile',
    description: 'Preview how teammates see your avatar, bio, and activity.',
    url: '/profile',
    category: 'getting-started',
    kind: 'link',
    tags: ['profile', 'public', 'avatar'],
  },
]
