// Generated by Wrangler by running `wrangler types`

interface Env {
	STUDIO_FROM_EMAIL: "billing@espeezy.com";
	STUDIO_REPLY_TO: "hello@espeezy.com";
	INBOUND_FORWARD_TO: "support@espeezy.com";
	SEND_EMAIL: SendEmail;
}
