const ASSETS_PATH = '/screenshots'

export const SCREENSHOT_ASSETS = {
  TASK_INTERFACE: `${ASSETS_PATH}/dash.png`,
  PROJECT_OVERVIEW: `${ASSETS_PATH}/dashdesktop.png`,
  CONTRIBUTION_METRICS: `${ASSETS_PATH}/hustledesktop.png`,
  /** Hero / gallery — project intelligence & contribution analytics */
  ANALYTICS_DASHBOARD: `${ASSETS_PATH}/hustledesktop.png`,
  TEAM_MANAGEMENT: `${ASSETS_PATH}/sidebaropenmobile.png`,
  DASHBOARD_VIEW: `${ASSETS_PATH}/dashboardhomemobile.png`,
  COLLABORATION_HUB: `${ASSETS_PATH}/networkmobile.png`,
  RESOURCE_CENTER: `${ASSETS_PATH}/hustlemobile.png`,
  ANALYTICS_ENGINE: `${ASSETS_PATH}/assistant.png`,
  USER_PROFILE: `${ASSETS_PATH}/profile.png`,
  SETTINGS_PANEL: `${ASSETS_PATH}/settingsdesktop.png`,
  NOTIFICATION_SYSTEM: `${ASSETS_PATH}/allset.png`,
  WORKFLOWS: `${ASSETS_PATH}/onboarding1.png`,
  DEEP_INSIGHTS: `${ASSETS_PATH}/settingsdetails.png`,
  PERFORMANCE_TRACKING: `${ASSETS_PATH}/hustlemobile2.png`,
  LIVE_UPDATES: `${ASSETS_PATH}/settingstheme.png`,
  GROUP_CHAT: `${ASSETS_PATH}/chilloutmobile.png`,
  ASSET_MARKETPLACE: `${ASSETS_PATH}/marketplacemobile.png`,
  ADMIN_CONSOLE: `${ASSETS_PATH}/admin.png`,
  GLOBAL_NETWORK: `${ASSETS_PATH}/homemobilecyber.png`,
  SIDE_HUSTLE: `${ASSETS_PATH}/settingstheme2.png`,
  EARNING_PORTAL: `${ASSETS_PATH}/settingstheme3.png`,
  TASK_MARKETPLACE: `${ASSETS_PATH}/chooseavatar.png`,
  INTERNAL_NODE: `${ASSETS_PATH}/chooseavatar2.png`,
  SYSTEM_STATUS: `${ASSETS_PATH}/terminal.png`,
  MOBILE_EXPERIENCE: `${ASSETS_PATH}/profilemobile.png`,
  SETTINGS_MOBILE: `${ASSETS_PATH}/settingsmobile.png`,
}
